### ISSUE TITLE
VirtualScope Code - We Need Each of You To Add The MIT License

### ISSUE THREAD

**Issue by kyle-hobbs** [huntress13/TeamPuma-VirtualScope#59]
Edit: Thanks!

**Comment by huntress13** [comment]
I am the sole original owner of this repo and I had other people in my group make a fork off of mine. I just added the licence.md file which includes everyone's name on it. I will advise the other contributors to do the same to theirs as well. Not entirely sure how it works in this scenario since I made them fork mine. I just want to make a note that we had no intention of keeping this as our own code. It just never crossed our mind to put this in a business account since we were more worried about just completing the task in class and making sure things work therefore it was not done intentionally. Furthermore, we also were not notified that there will be a continuation of this project in future capstone classes.

**Comment by kyle-hobbs** [comment]
Yeah I figured that, I just want to get that dealt with especially since the project hopefully will be used academically. Thanks!
